function featureNames = radiomic_feature_names()
%RADIOMIC_FEATURE_NAMES Return the 56 radiomic feature identifiers.
%
% The feature order matches the radiomic feature set used in the study.
% Features are extracted independently from the original B-mode ROI and
% from the LL, LH, HL, and HH level-1 Haar wavelet subbands.

featureNames = [ ...
    "IntensityEnergy2D", ...
    "DiscretisedIntensityEntropy2D", ...
    "MinimumIntensity2D", ...
    "TenthIntensityPercentile2D", ...
    "NinetiethIntensityPercentile2D", ...
    "MaximumIntensity2D", ...
    "MeanIntensity2D", ...
    "MedianIntensity2D", ...
    "IntensityInterquartileRange2D", ...
    "IntensityRange2D", ...
    "MeanAbsoluteDeviation2D", ...
    "RobustMeanAbsoluteDeviation2D", ...
    "RootMeanSquare2D", ...
    "IntensitySkewness2D", ...
    "IntensityKurtosis2D", ...
    "IntensityVariance2D", ...
    "DiscretisedIntensityUniformity2D", ...
    "AutoCorrelationAveraged2D", ...
    "JointAverageAveraged2D", ...
    "ClusterProminenceAveraged2D", ...
    "ClusterShadeAveraged2D", ...
    "ClusterTendencyAveraged2D", ...
    "ContrastAveraged2D", ...
    "CorrelationAveraged2D", ...
    "DifferenceAverageAveraged2D", ...
    "DifferenceEntropyAveraged2D", ...
    "DifferenceVarianceAveraged2D", ...
    "AngularSecondMomentAveraged2D", ...
    "JointEntropyAveraged2D", ...
    "InformationCorrelation1Averaged2D", ...
    "InformationCorrelation2Averaged2D", ...
    "InverseDifferenceMomentAveraged2D", ...
    "NormalisedInverseDifferenceMomentAveraged2D", ...
    "InverseDifferenceAveraged2D", ...
    "NormalisedInverseDifferenceAveraged2D", ...
    "InverseVarianceAveraged2D", ...
    "JointMaximumAveraged2D", ...
    "SumAverageAveraged2D", ...
    "SumEntropyAveraged2D", ...
    "JointVarianceAveraged2D", ...
    "ShortRunsEmphasisAveraged2D", ...
    "LongRunsEmphasisAveraged2D", ...
    "GrayLevelNonUniformityAveraged2D", ...
    "NormalisedGrayLevelNonUniformityAveraged2D", ...
    "RunLengthNonUniformityAveraged2D", ...
    "NormalisedRunLengthNonUniformityAveraged2D", ...
    "RunPercentageAveraged2D", ...
    "GrayLevelVarianceAveraged2D", ...
    "RunLengthVarianceAveraged2D", ...
    "RunEntropyAveraged2D", ...
    "LowGrayLevelRunEmphasisAveraged2D", ...
    "HighGrayLevelRunEmphasisAveraged2D", ...
    "ShortRunLowGrayLevelEmphasisAveraged2D", ...
    "ShortRunHighGrayLevelEmphasisAveraged2D", ...
    "LongRunLowGrayLevelEmphasisAveraged2D", ...
    "LongRunHighGrayLevelEmphasisAveraged2D" ...
];

assert(numel(featureNames) == 56, ...
    "The radiomic feature list must contain exactly 56 features.");

end