#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reference-grouped nested model development for full-reference ultrasound IQA.

The default invocation reproduces the study's grouped nested validation from the
exact public derived data stored under ``data/paper``. A separate ``custom``
mode applies the same grouped nested model-development protocol to a
``radiomic_dataset.mat`` generated by ``matlab/prepare_radiomic_dataset.m``
plus a CSV containing one subjective target per test sample.

Scientific protocol retained from the study:
- leave-one-reference-group-out outer evaluation;
- leave-one-training-reference-group-out inner model selection;
- six full-reference radiomic representations;
- training-only zero-variance filtering, z-scoring, deterministic Spearman
  redundancy filtering, and LASSO feature selection;
- five regression families and the prespecified hyperparameter grid;
- pooled inner RMSE as the primary selection criterion, followed by MAE,
  R2, and deterministic candidate order as tie-breakers.

The held-out reference group is never used to fit a representation,
preprocessing transform, feature selector, model, or hyperparameter choice.
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
import time
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import scipy
from scipy.io import loadmat
from scipy.stats import pearsonr, rankdata, spearmanr
import sklearn
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import Lasso, LinearRegression, Ridge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor


# -----------------------------------------------------------------------------
# Prespecified analysis configuration
# -----------------------------------------------------------------------------

MASTER_SEED = 20250111
SPEARMAN_THRESHOLD = 0.90

LASSO_ALPHAS = [
    1e-4,
    3e-4,
    1e-3,
    3e-3,
    1e-2,
    3e-2,
    1e-1,
    3e-1,
]

REPRESENTATIONS = [
    "signedDelta",
    "absoluteDelta",
    "normalizedDelta",
    "stableLogRatio",
    "jointRefTest",
    "jointRefTestDelta",
]

MODEL_CONFIGS: List[Dict[str, Any]] = []

MODEL_CONFIGS.append({"family": "MLR", "params": {}})

for alpha in [1e-3, 1e-2, 1e-1, 1, 10, 100, 1000]:
    MODEL_CONFIGS.append({
        "family": "Ridge",
        "params": {"alpha": alpha},
    })

for max_depth in [3, 5, 10]:
    for min_samples_split in [5, 10]:
        for min_samples_leaf in [1, 5]:
            MODEL_CONFIGS.append({
                "family": "DecisionTree",
                "params": {
                    "max_depth": max_depth,
                    "min_samples_split": min_samples_split,
                    "min_samples_leaf": min_samples_leaf,
                },
            })

for n_estimators in [100, 250]:
    for learning_rate in [0.05, 0.1, 0.2]:
        for max_depth in [2, 3]:
            MODEL_CONFIGS.append({
                "family": "GradientBoosting",
                "params": {
                    "n_estimators": n_estimators,
                    "learning_rate": learning_rate,
                    "max_depth": max_depth,
                },
            })

for C in [1, 10, 100]:
    for gamma in [1e-2, 1e-1, 1, 10]:
        MODEL_CONFIGS.append({
            "family": "RBF_SVR",
            "params": {"C": C, "gamma": gamma},
        })

assert len(MODEL_CONFIGS) == 44


# -----------------------------------------------------------------------------
# General utilities
# -----------------------------------------------------------------------------


def params_json(values: Dict[str, Any]) -> str:
    return json.dumps(values, sort_keys=True, separators=(",", ":"))


def safe_corr(y_true: np.ndarray, y_pred: np.ndarray, kind: str) -> float:
    y_true = np.asarray(y_true, dtype=float).ravel()
    y_pred = np.asarray(y_pred, dtype=float).ravel()

    if np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan

    if kind == "pearson":
        return float(pearsonr(y_true, y_pred).statistic)
    if kind == "spearman":
        return float(spearmanr(y_true, y_pred).statistic)
    raise ValueError(kind)


def regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=float).ravel()
    y_pred = np.asarray(y_pred, dtype=float).ravel()

    residual = y_true - y_pred
    mse = float(np.mean(residual**2))
    rmse = float(np.sqrt(mse))
    mae = float(np.mean(np.abs(residual)))

    ss_res = float(np.sum(residual**2))
    ss_tot = float(np.sum((y_true - np.mean(y_true))**2))
    r2 = np.nan if ss_tot == 0 else 1.0 - ss_res / ss_tot

    return {
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": float(r2),
        "PLCC": safe_corr(y_true, y_pred, "pearson"),
        "SROCC": safe_corr(y_true, y_pred, "spearman"),
    }


def deterministic_seed(outer_index: int, inner_index: int, model_index: int) -> int:
    return int(MASTER_SEED + outer_index * 100_000 + inner_index * 1_000 + model_index)


# -----------------------------------------------------------------------------
# Full-reference representations
# -----------------------------------------------------------------------------


@dataclass
class RepresentationFit:
    name: str
    shift: Optional[np.ndarray] = None
    margin: Optional[np.ndarray] = None


def representation_feature_names(rep: str, base_names: Sequence[str]) -> List[str]:
    base_names = list(base_names)
    if rep in {"signedDelta", "absoluteDelta", "normalizedDelta", "stableLogRatio"}:
        return [f"{rep}__{name}" for name in base_names]
    if rep == "jointRefTest":
        return [f"ref__{name}" for name in base_names] + [f"test__{name}" for name in base_names]
    if rep == "jointRefTestDelta":
        return (
            [f"ref__{name}" for name in base_names]
            + [f"test__{name}" for name in base_names]
            + [f"delta__{name}" for name in base_names]
        )
    raise ValueError(f"Unknown representation: {rep}")


def fit_representation(rep: str, X_ref_train: np.ndarray, X_test_train: np.ndarray) -> RepresentationFit:
    if rep != "stableLogRatio":
        return RepresentationFit(name=rep)

    both = np.vstack([X_ref_train, X_test_train])
    min_train = np.min(both, axis=0)
    q25 = np.percentile(both, 25, axis=0)
    q75 = np.percentile(both, 75, axis=0)
    iqr = q75 - q25
    median_abs = np.median(np.abs(both), axis=0)

    scale = np.maximum.reduce([iqr, median_abs, np.ones_like(iqr)])
    margin = 1e-6 * scale
    shift = np.maximum(0.0, -min_train) + margin

    return RepresentationFit(name=rep, shift=shift, margin=margin)


def apply_representation(
    fit: RepresentationFit,
    X_ref: np.ndarray,
    X_test: np.ndarray,
) -> np.ndarray:
    rep = fit.name

    if rep == "signedDelta":
        return X_ref - X_test

    if rep == "absoluteDelta":
        return np.abs(X_ref - X_test)

    if rep == "normalizedDelta":
        denominator = np.abs(X_ref) + np.abs(X_test)
        out = np.zeros_like(denominator, dtype=float)
        nonzero = denominator != 0
        out[nonzero] = (X_ref[nonzero] - X_test[nonzero]) / denominator[nonzero]
        return out

    if rep == "stableLogRatio":
        if fit.shift is None or fit.margin is None:
            raise RuntimeError("stableLogRatio was applied before fitting its training parameters.")
        ref_stable = np.maximum(X_ref + fit.shift, fit.margin)
        test_stable = np.maximum(X_test + fit.shift, fit.margin)
        return np.log(ref_stable) - np.log(test_stable)

    if rep == "jointRefTest":
        return np.hstack([X_ref, X_test])

    if rep == "jointRefTestDelta":
        return np.hstack([X_ref, X_test, X_ref - X_test])

    raise ValueError(f"Unknown representation: {rep}")


# -----------------------------------------------------------------------------
# Training-only preprocessing
# -----------------------------------------------------------------------------


@dataclass
class Preprocessor:
    keep_nonconstant: np.ndarray
    mean_: np.ndarray
    std_: np.ndarray
    keep_spearman: np.ndarray
    input_feature_names: List[str]


def greedy_spearman_keep(X_train_z: np.ndarray, threshold: float) -> np.ndarray:
    n_features = X_train_z.shape[1]
    if n_features == 1:
        return np.array([0], dtype=int)

    ranks = rankdata(X_train_z, axis=0, method="average")
    rank_std = np.std(ranks, axis=0, ddof=0)
    valid = np.where(np.isfinite(rank_std) & (rank_std > 0))[0]

    if valid.size == 0:
        raise ValueError("All features became rank-degenerate before Spearman filtering.")
    if valid.size == 1:
        return valid.astype(int)

    R = ranks[:, valid]
    R_mean = np.mean(R, axis=0)
    R_std = np.std(R, axis=0, ddof=0)
    Z = (R - R_mean) / R_std
    corr = (Z.T @ Z) / Z.shape[0]
    corr = np.clip(corr, -1.0, 1.0)

    kept_local: List[int] = []
    for j in range(valid.size):
        if not kept_local or np.all(np.abs(corr[j, kept_local]) <= threshold):
            kept_local.append(j)

    return valid[np.asarray(kept_local, dtype=int)].astype(int)


def fit_preprocessor(X_train: np.ndarray, feature_names: Sequence[str]) -> Tuple[Preprocessor, np.ndarray]:
    X_train = np.asarray(X_train, dtype=float)
    if not np.all(np.isfinite(X_train)):
        raise ValueError("Non-finite training feature encountered before preprocessing.")

    std0 = np.std(X_train, axis=0, ddof=0)
    keep_nonconstant = np.where(np.isfinite(std0) & (std0 > 0))[0]
    if keep_nonconstant.size == 0:
        raise ValueError("All features are zero/non-finite variance.")

    X1 = X_train[:, keep_nonconstant]
    mean_ = np.mean(X1, axis=0)
    std_ = np.std(X1, axis=0, ddof=0)
    if np.any(~np.isfinite(std_)) or np.any(std_ <= 0):
        raise ValueError("Invalid standard deviation after zero-variance filtering.")

    Xz = (X1 - mean_) / std_
    keep_spearman = greedy_spearman_keep(Xz, SPEARMAN_THRESHOLD)
    Xout = Xz[:, keep_spearman]

    return (
        Preprocessor(
            keep_nonconstant=keep_nonconstant,
            mean_=mean_,
            std_=std_,
            keep_spearman=keep_spearman,
            input_feature_names=list(feature_names),
        ),
        Xout,
    )


def apply_preprocessor(prep: Preprocessor, X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=float)
    if not np.all(np.isfinite(X)):
        raise ValueError("Non-finite feature encountered before preprocessing.")

    X1 = X[:, prep.keep_nonconstant]
    Xz = (X1 - prep.mean_) / prep.std_
    Xout = Xz[:, prep.keep_spearman]

    if not np.all(np.isfinite(Xout)):
        raise ValueError("Non-finite feature encountered after preprocessing.")
    return Xout


def names_after_preprocessor(prep: Preprocessor) -> List[str]:
    after_nonconstant = [prep.input_feature_names[i] for i in prep.keep_nonconstant]
    return [after_nonconstant[i] for i in prep.keep_spearman]


# -----------------------------------------------------------------------------
# Feature selection and regression models
# -----------------------------------------------------------------------------


def fit_lasso_selector(X_train: np.ndarray, y_train: np.ndarray, alpha: float) -> np.ndarray:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=ConvergenceWarning)
        selector = Lasso(
            alpha=float(alpha),
            fit_intercept=True,
            max_iter=100_000,
            tol=1e-7,
            selection="cyclic",
        )
        selector.fit(X_train, y_train)
    return np.flatnonzero(selector.coef_ != 0.0)


def make_model(config: Dict[str, Any], random_state: int):
    family = config["family"]
    p = dict(config["params"])

    if family == "MLR":
        return LinearRegression()
    if family == "Ridge":
        return Ridge(alpha=float(p["alpha"]))
    if family == "DecisionTree":
        return DecisionTreeRegressor(
            max_depth=int(p["max_depth"]),
            min_samples_split=int(p["min_samples_split"]),
            min_samples_leaf=int(p["min_samples_leaf"]),
            random_state=random_state,
        )
    if family == "GradientBoosting":
        return GradientBoostingRegressor(
            n_estimators=int(p["n_estimators"]),
            learning_rate=float(p["learning_rate"]),
            max_depth=int(p["max_depth"]),
            random_state=random_state,
            loss="squared_error",
        )
    if family == "RBF_SVR":
        return SVR(kernel="rbf", C=float(p["C"]), gamma=float(p["gamma"]))

    raise ValueError(f"Unknown model family: {family}")


# -----------------------------------------------------------------------------
# Data loading
# -----------------------------------------------------------------------------



def _matlab_cell_strings(value: np.ndarray) -> List[str]:
    """Convert a MATLAB cell/string array loaded by scipy.io.loadmat to Python strings."""
    arr = np.asarray(value)
    out: List[str] = []

    for item in arr.ravel(order="F"):
        if isinstance(item, str):
            out.append(item)
            continue

        if isinstance(item, bytes):
            out.append(item.decode("utf-8"))
            continue

        if isinstance(item, np.ndarray):
            squeezed = np.asarray(item).squeeze()

            if squeezed.ndim == 0:
                out.append(str(squeezed.item()))
                continue

            if squeezed.dtype.kind in {"U", "S"}:
                flat = squeezed.ravel(order="F").tolist()
                if len(flat) == 1:
                    out.append(str(flat[0]))
                else:
                    out.append("".join(str(x) for x in flat))
                continue

            if squeezed.size == 1:
                out.append(str(squeezed.item()))
                continue

        out.append(str(item))

    return out


def load_paper_dataset(paper_file: Path) -> Tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    List[str],
    List[str],
]:
    """Load exact derived numerical inputs used for paper reproduction."""
    if not paper_file.is_file():
        raise FileNotFoundError(f"Paper modeling data file not found: {paper_file}")

    data = loadmat(paper_file)

    required = {
        "X_reference",
        "X_test",
        "y",
        "sample_id",
        "group_index",
        "feature_names",
        "reference_labels",
    }
    missing = sorted(required.difference(data.keys()))
    if missing:
        raise ValueError(
            "paper_modeling_data.mat is missing required variable(s): "
            + ", ".join(missing)
        )

    X_reference = np.asfortranarray(np.asarray(data["X_reference"], dtype=float))
    X_test = np.asfortranarray(np.asarray(data["X_test"], dtype=float))
    y = np.asarray(data["y"], dtype=float).ravel(order="F")
    sample_id = np.asarray(data["sample_id"]).ravel(order="F")
    group_index = np.asarray(data["group_index"]).ravel(order="F").astype(int)

    feature_names = _matlab_cell_strings(data["feature_names"])
    group_order = _matlab_cell_strings(data["reference_labels"])

    if X_reference.ndim != 2 or X_test.ndim != 2:
        raise ValueError("X_reference and X_test must be 2-D matrices.")
    if X_test.shape[0] != y.size:
        raise ValueError("X_test row count must equal the number of targets.")
    if sample_id.size != y.size or group_index.size != y.size:
        raise ValueError("Sample/group identifiers must match the number of targets.")
    if X_reference.shape[1] != X_test.shape[1]:
        raise ValueError("Reference and test radiomic feature dimensions differ.")
    if X_test.shape[1] != len(feature_names):
        raise ValueError("Feature-name count does not match radiomic feature dimension.")
    if X_test.shape[1] != 280:
        raise ValueError("Expected exactly 280 radiomic descriptors per image.")
    if len(set(feature_names)) != len(feature_names):
        raise ValueError("Duplicate radiomic feature names found.")
    if len(group_order) != X_reference.shape[0]:
        raise ValueError("Reference-label count does not match X_reference rows.")
    if len(group_order) < 3:
        raise ValueError("Grouped nested validation requires at least three reference groups.")

    expected_groups = np.arange(1, len(group_order) + 1, dtype=int)
    observed_groups = np.unique(group_index)
    if not np.array_equal(observed_groups, expected_groups):
        raise ValueError(
            "group_index must contain consecutive one-based group IDs matching reference_labels."
        )

    if np.any(group_index < 1) or np.any(group_index > X_reference.shape[0]):
        raise ValueError("group_index contains an invalid reference-group index.")

    # Reconstruct the per-sample reference matrix from exact stored doubles.
    # Column-major layout matches scipy.io.loadmat behavior for the frozen MAT.
    X_ref = np.asfortranarray(X_reference[group_index - 1, :], dtype=float)

    if not (
        np.all(np.isfinite(X_ref))
        and np.all(np.isfinite(X_test))
        and np.all(np.isfinite(y))
    ):
        raise ValueError("Non-finite value found in paper modeling data.")

    return X_ref, X_test, y, sample_id, group_index, feature_names, group_order


def load_custom_dataset(
    radiomic_file: Path,
    scores_file: Path,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    List[str],
    List[str],
]:
    """Load a custom MATLAB radiomic dataset and align its subjective targets.

    ``radiomic_file`` must be generated by ``prepare_radiomic_dataset.m`` and
    contain exact reference/test radiomic doubles plus plain MATLAB metadata.
    ``scores_file`` must contain:
        SampleID, ReferenceID, SubjectiveTarget
    """
    if not radiomic_file.is_file():
        raise FileNotFoundError(f"Custom radiomic dataset not found: {radiomic_file}")
    if not scores_file.is_file():
        raise FileNotFoundError(f"Custom subjective-score file not found: {scores_file}")

    data = loadmat(radiomic_file)

    required = {
        "X_reference",
        "X_test",
        "sample_id",
        "group_index",
        "feature_names",
        "reference_labels",
    }
    missing = sorted(required.difference(data.keys()))
    if missing:
        raise ValueError(
            "Custom radiomic_dataset.mat is missing required variable(s): "
            + ", ".join(missing)
        )

    X_reference = np.asfortranarray(np.asarray(data["X_reference"], dtype=float))
    X_test = np.asfortranarray(np.asarray(data["X_test"], dtype=float))
    sample_ids = _matlab_cell_strings(data["sample_id"])
    group_index = np.asarray(data["group_index"]).ravel(order="F").astype(int)
    feature_names = _matlab_cell_strings(data["feature_names"])
    group_order = _matlab_cell_strings(data["reference_labels"])

    if X_reference.ndim != 2 or X_test.ndim != 2:
        raise ValueError("X_reference and X_test must be 2-D matrices.")
    if X_test.shape[0] != len(sample_ids):
        raise ValueError("X_test row count must equal the number of SampleID values.")
    if group_index.size != len(sample_ids):
        raise ValueError("group_index length must equal the number of test samples.")
    if X_reference.shape[1] != X_test.shape[1]:
        raise ValueError("Reference and test radiomic feature dimensions differ.")
    if X_test.shape[1] != len(feature_names):
        raise ValueError("Feature-name count does not match radiomic feature dimension.")
    if X_test.shape[1] != 280:
        raise ValueError(
            "Expected exactly 280 radiomic descriptors per image. "
            "Generate the custom dataset with prepare_radiomic_dataset.m."
        )
    if len(set(feature_names)) != len(feature_names):
        raise ValueError("Duplicate radiomic feature names found.")
    if len(group_order) != X_reference.shape[0]:
        raise ValueError("Reference-label count does not match X_reference rows.")
    if len(group_order) < 3:
        raise ValueError(
            "Grouped nested validation requires at least three reference groups."
        )
    if len(set(sample_ids)) != len(sample_ids):
        raise ValueError("SampleID values in radiomic_dataset.mat must be unique.")
    if len(set(group_order)) != len(group_order):
        raise ValueError("Reference labels in radiomic_dataset.mat must be unique.")

    expected_groups = np.arange(1, len(group_order) + 1, dtype=int)
    observed_groups = np.unique(group_index)
    if not np.array_equal(observed_groups, expected_groups):
        raise ValueError(
            "group_index must contain consecutive one-based group IDs matching "
            "reference_labels."
        )

    if np.any(group_index < 1) or np.any(group_index > X_reference.shape[0]):
        raise ValueError("group_index contains an invalid reference-group index.")

    scores = pd.read_csv(
        scores_file,
        dtype={"SampleID": str, "ReferenceID": str},
    )

    required_score_columns = {"SampleID", "ReferenceID", "SubjectiveTarget"}
    missing_score_columns = sorted(required_score_columns.difference(scores.columns))
    if missing_score_columns:
        raise ValueError(
            "Custom subjective-score CSV is missing required column(s): "
            + ", ".join(missing_score_columns)
        )

    scores = scores[["SampleID", "ReferenceID", "SubjectiveTarget"]].copy()
    scores["SampleID"] = scores["SampleID"].astype(str)
    scores["ReferenceID"] = scores["ReferenceID"].astype(str)

    if scores["SampleID"].duplicated().any():
        raise ValueError("SampleID values in the subjective-score CSV must be unique.")
    if scores["SampleID"].isna().any() or scores["ReferenceID"].isna().any():
        raise ValueError("Subjective-score CSV contains missing SampleID or ReferenceID.")

    score_sample_ids = set(scores["SampleID"])
    mat_sample_ids = set(sample_ids)

    missing_scores = sorted(mat_sample_ids - score_sample_ids)
    extra_scores = sorted(score_sample_ids - mat_sample_ids)

    if missing_scores:
        preview = ", ".join(missing_scores[:10])
        raise ValueError(
            f"Missing subjective targets for {len(missing_scores)} sample(s): {preview}"
        )
    if extra_scores:
        preview = ", ".join(extra_scores[:10])
        raise ValueError(
            f"Subjective-score CSV contains {len(extra_scores)} unknown sample(s): {preview}"
        )

    score_lookup = scores.set_index("SampleID")
    aligned_scores = score_lookup.loc[sample_ids]

    expected_reference_labels = np.asarray(
        [group_order[i - 1] for i in group_index],
        dtype=object,
    )
    observed_reference_labels = aligned_scores["ReferenceID"].astype(str).to_numpy()

    if not np.array_equal(expected_reference_labels, observed_reference_labels):
        mismatch = np.where(expected_reference_labels != observed_reference_labels)[0]
        i = int(mismatch[0])
        raise ValueError(
            "ReferenceID mismatch between radiomic_dataset.mat and subjective-score "
            f"CSV for SampleID '{sample_ids[i]}': expected "
            f"'{expected_reference_labels[i]}', found "
            f"'{observed_reference_labels[i]}'."
        )

    y = pd.to_numeric(
        aligned_scores["SubjectiveTarget"],
        errors="raise",
    ).to_numpy(dtype=float)

    # Reconstruct one reference feature vector per test sample from the exact
    # doubles stored by MATLAB. Keep column-major layout for numerical
    # consistency with the paper reproduction path.
    X_ref = np.asfortranarray(X_reference[group_index - 1, :], dtype=float)
    X_test = np.asfortranarray(X_test, dtype=float)

    if not (
        np.all(np.isfinite(X_ref))
        and np.all(np.isfinite(X_test))
        and np.all(np.isfinite(y))
    ):
        raise ValueError("Non-finite value found in custom modeling data.")

    sample_id = np.asarray(sample_ids, dtype=object)

    return X_ref, X_test, y, sample_id, group_index, feature_names, group_order


# -----------------------------------------------------------------------------
# Nested grouped model development
# -----------------------------------------------------------------------------


def run_inner_search(
    outer_index: int,
    outer_train_idx: np.ndarray,
    X_ref: np.ndarray,
    X_test: np.ndarray,
    y: np.ndarray,
    group_index: np.ndarray,
    base_feature_names: List[str],
) -> Dict[str, Any]:
    outer_train_idx = np.asarray(outer_train_idx, dtype=int)
    train_groups = sorted(np.unique(group_index[outer_train_idx]).astype(int).tolist())
    n_inner_folds = len(train_groups)

    if n_inner_folds < 2:
        raise ValueError("At least two training reference groups are required for inner grouped validation.")

    global_to_local = {int(gidx): i for i, gidx in enumerate(outer_train_idx.tolist())}
    n_outer_train = len(outer_train_idx)

    all_rows: List[Dict[str, Any]] = []
    candidate_order_counter = 0

    for rep in REPRESENTATIONS:
        rep_names = representation_feature_names(rep, base_feature_names)

        pred_store: Dict[Tuple[int, int], np.ndarray] = {}
        valid_store: Dict[Tuple[int, int], bool] = {}
        selected_counts_store: Dict[Tuple[int, int], List[int]] = {}

        for li in range(len(LASSO_ALPHAS)):
            for mi in range(len(MODEL_CONFIGS)):
                key = (li, mi)
                pred_store[key] = np.full(n_outer_train, np.nan, dtype=float)
                valid_store[key] = True
                selected_counts_store[key] = []

        for inner_number, held_inner_group in enumerate(train_groups, start=1):
            inner_val_global = outer_train_idx[group_index[outer_train_idx] == held_inner_group]
            inner_train_global = outer_train_idx[group_index[outer_train_idx] != held_inner_group]

            if len(inner_train_global) == 0 or len(inner_val_global) == 0:
                raise RuntimeError("Invalid grouped inner split.")

            rep_fit = fit_representation(rep, X_ref[inner_train_global], X_test[inner_train_global])
            Xtr_rep = apply_representation(rep_fit, X_ref[inner_train_global], X_test[inner_train_global])
            Xva_rep = apply_representation(rep_fit, X_ref[inner_val_global], X_test[inner_val_global])

            prep, Xtr_pre = fit_preprocessor(Xtr_rep, rep_names)
            Xva_pre = apply_preprocessor(prep, Xva_rep)

            val_local_positions = np.asarray(
                [global_to_local[int(g)] for g in inner_val_global],
                dtype=int,
            )
            ytr = y[inner_train_global]

            for li, lasso_alpha in enumerate(LASSO_ALPHAS):
                selected = fit_lasso_selector(Xtr_pre, ytr, lasso_alpha)
                if selected.size == 0:
                    for mi in range(len(MODEL_CONFIGS)):
                        valid_store[(li, mi)] = False
                    continue

                Xtr_sel = Xtr_pre[:, selected]
                Xva_sel = Xva_pre[:, selected]

                for mi, model_cfg in enumerate(MODEL_CONFIGS):
                    key = (li, mi)
                    if not valid_store[key]:
                        continue

                    seed = deterministic_seed(outer_index, inner_number, mi)
                    model = make_model(model_cfg, seed)

                    try:
                        with warnings.catch_warnings():
                            warnings.simplefilter("ignore")
                            model.fit(Xtr_sel, ytr)
                            pred = np.asarray(model.predict(Xva_sel), dtype=float).ravel()

                        if pred.shape[0] != len(inner_val_global) or not np.all(np.isfinite(pred)):
                            valid_store[key] = False
                            continue

                        pred_store[key][val_local_positions] = pred
                        selected_counts_store[key].append(int(selected.size))
                    except Exception:
                        valid_store[key] = False

        y_outer_train = y[outer_train_idx]

        for li, lasso_alpha in enumerate(LASSO_ALPHAS):
            for mi, model_cfg in enumerate(MODEL_CONFIGS):
                candidate_order_counter += 1
                key = (li, mi)
                preds = pred_store[key]

                valid = (
                    valid_store[key]
                    and np.all(np.isfinite(preds))
                    and len(selected_counts_store[key]) == n_inner_folds
                )

                row: Dict[str, Any] = {
                    "CandidateOrder": candidate_order_counter,
                    "Representation": rep,
                    "LassoAlpha": lasso_alpha,
                    "ModelFamily": model_cfg["family"],
                    "ModelParamsJSON": params_json(model_cfg["params"]),
                    "Valid": bool(valid),
                }

                if valid:
                    metrics = regression_metrics(y_outer_train, preds)
                    row.update({
                        "InnerMAE": metrics["MAE"],
                        "InnerRMSE": metrics["RMSE"],
                        "InnerR2": metrics["R2"],
                    })
                else:
                    row.update({"InnerMAE": np.nan, "InnerRMSE": np.nan, "InnerR2": np.nan})

                all_rows.append(row)

    leaderboard = pd.DataFrame(all_rows)
    valid_lb = leaderboard[leaderboard["Valid"]].copy()
    if valid_lb.empty:
        raise RuntimeError(f"Outer fold {outer_index}: no valid inner candidate.")

    valid_lb["_sort_r2"] = -valid_lb["InnerR2"]
    valid_lb = valid_lb.sort_values(
        by=["InnerRMSE", "InnerMAE", "_sort_r2", "CandidateOrder"],
        ascending=[True, True, True, True],
        kind="mergesort",
    )
    return valid_lb.iloc[0].drop(labels=["_sort_r2"]).to_dict()


def fit_predict_outer(
    outer_index: int,
    best: Dict[str, Any],
    train_idx: np.ndarray,
    test_idx: np.ndarray,
    X_ref: np.ndarray,
    X_test: np.ndarray,
    y: np.ndarray,
    base_feature_names: List[str],
) -> Tuple[np.ndarray, List[str]]:
    rep = str(best["Representation"])
    lasso_alpha = float(best["LassoAlpha"])
    family = str(best["ModelFamily"])
    model_params = json.loads(str(best["ModelParamsJSON"]))

    rep_names = representation_feature_names(rep, base_feature_names)
    rep_fit = fit_representation(rep, X_ref[train_idx], X_test[train_idx])
    Xtr_rep = apply_representation(rep_fit, X_ref[train_idx], X_test[train_idx])
    Xte_rep = apply_representation(rep_fit, X_ref[test_idx], X_test[test_idx])

    prep, Xtr_pre = fit_preprocessor(Xtr_rep, rep_names)
    Xte_pre = apply_preprocessor(prep, Xte_rep)

    selected = fit_lasso_selector(Xtr_pre, y[train_idx], lasso_alpha)
    if selected.size == 0:
        raise RuntimeError(
            f"Outer fold {outer_index}: selected candidate retains zero features after outer refit."
        )

    matching_model_index = None
    selected_cfg = None
    for mi, cfg in enumerate(MODEL_CONFIGS):
        if cfg["family"] == family and params_json(cfg["params"]) == params_json(model_params):
            matching_model_index = mi
            selected_cfg = cfg
            break

    if selected_cfg is None or matching_model_index is None:
        raise RuntimeError("Could not recover selected model configuration.")

    seed = deterministic_seed(outer_index, 99, matching_model_index)
    model = make_model(selected_cfg, seed)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model.fit(Xtr_pre[:, selected], y[train_idx])
        pred = np.asarray(model.predict(Xte_pre[:, selected]), dtype=float).ravel()

    if pred.shape[0] != len(test_idx) or not np.all(np.isfinite(pred)):
        raise RuntimeError(f"Outer fold {outer_index}: invalid outer predictions.")

    preprocessed_names = names_after_preprocessor(prep)
    selected_names = [preprocessed_names[i] for i in selected]
    return pred, selected_names


# -----------------------------------------------------------------------------
# Command-line execution
# -----------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    script_path = Path(__file__).resolve()
    repo_root = script_path.parents[1]

    parser = argparse.ArgumentParser(
        description="Run reference-grouped nested model development on radiomic FR-IQA data."
    )
    parser.add_argument(
        "--input-mode",
        choices=["paper", "custom"],
        default="paper",
        help=(
            "Input source. 'paper' reproduces the study from exact public derived "
            "data; 'custom' reads radiomic_dataset.mat generated by the MATLAB "
            "wrapper plus a subjective-score CSV."
        ),
    )
    parser.add_argument(
        "--paper-data",
        type=Path,
        default=repo_root / "data" / "paper" / "paper_modeling_data.mat",
        help="Exact derived MAT file used for paper reproduction.",
    )
    parser.add_argument(
        "--custom-data",
        type=Path,
        default=repo_root / "data" / "user_input" / "radiomic_dataset.mat",
        help=(
            "Custom radiomic_dataset.mat generated by "
            "matlab/prepare_radiomic_dataset.m."
        ),
    )
    parser.add_argument(
        "--scores-file",
        type=Path,
        default=repo_root / "data" / "user_input" / "subjective_scores.csv",
        help=(
            "Custom CSV containing SampleID, ReferenceID, and SubjectiveTarget."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory in which analysis outputs are written. Defaults to "
            "results/ for paper mode and results/custom/ for custom mode."
        ),
    )
    return parser.parse_args()

def main() -> None:
    args = parse_args()
    start_time = time.time()

    if args.input_mode == "paper":
        X_ref, X_test, y, sample_id, group_index, feature_names, group_order = load_paper_dataset(
            args.paper_data.resolve()
        )
    else:
        X_ref, X_test, y, sample_id, group_index, feature_names, group_order = load_custom_dataset(
            args.custom_data.resolve(),
            args.scores_file.resolve(),
        )

    n_samples = len(y)
    n_groups = len(group_order)
    all_predictions = np.full(n_samples, np.nan, dtype=float)

    fold_metric_rows: List[Dict[str, Any]] = []
    selected_pipeline_rows: List[Dict[str, Any]] = []
    selected_feature_rows: List[Dict[str, Any]] = []

    print(f"Input mode: {args.input_mode}")
    print(f"Samples: {n_samples}")
    print(f"Reference groups: {n_groups}")
    print(f"Radiomic descriptors per image: {X_ref.shape[1]}")
    print(f"Candidate pipelines per outer fold: {len(REPRESENTATIONS) * len(LASSO_ALPHAS) * len(MODEL_CONFIGS)}")
    print(f"Master seed: {MASTER_SEED}\n")

    for outer_index, held_group in enumerate(group_order, start=1):
        fold_start = time.time()
        test_idx = np.where(group_index == outer_index)[0]
        train_idx = np.where(group_index != outer_index)[0]

        print(f"Outer fold {outer_index}/{n_groups}: held out {held_group}")
        print(f"  train={len(train_idx)} | test={len(test_idx)}")

        best = run_inner_search(
            outer_index=outer_index,
            outer_train_idx=train_idx,
            X_ref=X_ref,
            X_test=X_test,
            y=y,
            group_index=group_index,
            base_feature_names=feature_names,
        )

        pred, selected_names = fit_predict_outer(
            outer_index=outer_index,
            best=best,
            train_idx=train_idx,
            test_idx=test_idx,
            X_ref=X_ref,
            X_test=X_test,
            y=y,
            base_feature_names=feature_names,
        )

        all_predictions[test_idx] = pred
        metrics = regression_metrics(y[test_idx], pred)

        print(
            f"  selected: {best['Representation']} | LASSO={best['LassoAlpha']} | "
            f"{best['ModelFamily']} {best['ModelParamsJSON']} | features={len(selected_names)}"
        )
        print(
            f"  held-out RMSE={metrics['RMSE']:.6f} | R2={metrics['R2']:.6f} | "
            f"PLCC={metrics['PLCC']:.6f} | SROCC={metrics['SROCC']:.6f}"
        )
        print(f"  elapsed={((time.time() - fold_start) / 60):.1f} min\n")

        fold_metric_rows.append({
            "OuterFold": outer_index,
            "HeldOutReferenceID": held_group,
            "NTrain": len(train_idx),
            "NTest": len(test_idx),
            **metrics,
        })

        selected_pipeline_rows.append({
            "OuterFold": outer_index,
            "HeldOutReferenceID": held_group,
            "Representation": best["Representation"],
            "LassoAlpha": best["LassoAlpha"],
            "ModelFamily": best["ModelFamily"],
            "ModelParamsJSON": best["ModelParamsJSON"],
            "SelectedFeatureCount": len(selected_names),
            "InnerRMSE": best["InnerRMSE"],
            "InnerMAE": best["InnerMAE"],
            "InnerR2": best["InnerR2"],
        })

        for rank, name in enumerate(selected_names, start=1):
            selected_feature_rows.append({
                "OuterFold": outer_index,
                "HeldOutReferenceID": held_group,
                "SelectionRank": rank,
                "FeatureName": name,
            })

    if not np.all(np.isfinite(all_predictions)):
        raise RuntimeError("Some outer predictions were not generated.")

    aggregate = regression_metrics(y, all_predictions)

    if args.output_dir is None:
        repo_root = Path(__file__).resolve().parents[1]
        output_dir = (
            repo_root / "results"
            if args.input_mode == "paper"
            else repo_root / "results" / "custom"
        )
    else:
        output_dir = args.output_dir.resolve()

    output_dir.mkdir(parents=True, exist_ok=True)

    predictions = pd.DataFrame({
        "SampleID": sample_id,
        "ReferenceID": [group_order[i - 1] for i in group_index],
        "SubjectiveTarget": y,
        "OutOfReferencePrediction": all_predictions,
        "Residual": y - all_predictions,
    })
    predictions.to_csv(output_dir / "predictions.csv", index=False)
    pd.DataFrame(fold_metric_rows).to_csv(output_dir / "fold_metrics.csv", index=False)
    pd.DataFrame(selected_pipeline_rows).to_csv(output_dir / "selected_pipelines.csv", index=False)
    pd.DataFrame(selected_feature_rows).to_csv(output_dir / "selected_features.csv", index=False)

    versions = {
        "python": sys.version,
        "platform": platform.platform(),
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "scipy": scipy.__version__,
        "scikit_learn": sklearn.__version__,
        "master_seed": MASTER_SEED,
    }
    (output_dir / "software_versions.json").write_text(
        json.dumps(versions, indent=2, sort_keys=True),
        encoding="utf-8",
    )

    summary = {
        "InputMode": args.input_mode,
        "N": n_samples,
        "ReferenceGroups": n_groups,
        "MAE": aggregate["MAE"],
        "RMSE": aggregate["RMSE"],
        "R2": aggregate["R2"],
        "PLCC": aggregate["PLCC"],
        "SROCC": aggregate["SROCC"],
        "MasterSeed": MASTER_SEED,
        "ElapsedMinutes": (time.time() - start_time) / 60.0,
    }
    (output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True),
        encoding="utf-8",
    )

    print("Aggregate out-of-reference performance")
    print(f"  MAE   = {aggregate['MAE']:.8f}")
    print(f"  RMSE  = {aggregate['RMSE']:.8f}")
    print(f"  R2    = {aggregate['R2']:.8f}")
    print(f"  PLCC  = {aggregate['PLCC']:.8f}")
    print(f"  SROCC = {aggregate['SROCC']:.8f}")
    print(f"\nOutputs written to: {output_dir}")


if __name__ == "__main__":
    main()
